import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import { ClerkProvider } from '@clerk/clerk-react'

import './index.css'
import App from './App.jsx'

// Register the service worker generated by vite-plugin-pwa.
// immediate: true → try to register on page load without waiting for 'load' event.
registerSW({
  immediate: true,
})

// Import and clean publishable key
const PUBLISHABLE_KEY = import.meta.env.VITE_CLERK_PUBLISHABLE_KEY?.trim()

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <ClerkProvider 
      publishableKey={PUBLISHABLE_KEY} 
      afterSignOutUrl="/"
      signInUrl="/login"
      signUpUrl="/signup"
    >
      <App />
    </ClerkProvider>
  </StrictMode>
)
